#pragma once

#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include "Interface.h"
#include <libconfig.h>

bool HtmlTemplateUseStock;

typedef struct _HTML_TEMPLATE_MIME_TYPE {
	char *extension;
	char *type;
} HTML_TEMPLATE_MIME_TYPE;

HTML_TEMPLATE_MIME_TYPE *HtmlTemplateMimeTypes;
size_t HtmlTemplateMimeTypesSize;

typedef enum _HTML_TEMPLATE_COMPONENT_IDENTIFIER {
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_VERSION = 0,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CURRENT_PAGE = 1,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_HOME_ACTIVE = 2,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_UPROXIES_ACTIVE = 3,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_PROXIES_ACTIVE = 4,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_SOURCES_ACTIVE = 5,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_STATS_ACTIVE = 6,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_USER = 7,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_COUNT_UPROXIES = 8,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_COUNT_PROXIES = 9,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_UPROXIES_HEAD = 10,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_UPROXIES_TABLE_ITEMS_START = 11,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_UPROXIES_TABLE_ITEMS_END = 12,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TABLE_ODD = 13,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TABLE_EVEN = 14,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TABLE_OK = 15,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TABLE_WARN = 16,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TABLE_ERR = 17,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_UPROXIES_ITEM = 18,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PROXIES_HEAD = 19,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PROXIES_TABLE_ITEMS_START = 20,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PROXIES_TABLE_ITEMS_END = 21,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PROXIES_ITEM = 22,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PRXSRC_HEAD = 23,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PRXSRC_TABLE_ITEMS_START = 24,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PRXSRC_TABLE_ITEMS_END = 25,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_PRXSRC_ITEM = 26,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_STATIC = 27,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_TABLE_BREAK = 28,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_STATS_GEO_HEAD = 29,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_STATS_GEO_TABLE_ITEMS_START = 30,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_STATS_GEO_TABLE_ITEMS_END = 31,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_STATS_GEO_ITEM = 32,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_IP = 33,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_PORT = 34,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_TYPE = 35,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COUNTRY_LOWER = 36,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COUNTRY_UPPER = 37,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_LIVE_SINCE = 38,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_LAST_CHECKED = 39,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_CONNECT_TIMEOUT = 40,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_HTTP_S_TIMEOUT = 41,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_SUCCESSFUL_CHECKS = 42,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_FAILED_CHECKS = 43,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_RETRIES = 44,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_UID = 45,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COUNTRY_FULL = 46,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_SIZE_UPROXIES = 47,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_SIZE_PROXIES = 48,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_AUTH_COOKIE = 49,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_MSG_INTERVAL = 50,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_PROXY_ADD = 51,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_UPROXY_ADD = 52,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_PROXY_REMOVE = 53,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_SUB_UPROXY_REMOVE = 54,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_ENABLED = 55,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_DISABLED = 56,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CFG_TOOLS_ACTIVE = 57,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COND_INVALID_CERT = 58,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COND_INVALID_CERT_FINGERPRINT = 59,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_ELSE_COND_INVALID_CERT = 60,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_END_COND_INVALID_CERT = 61,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_CHECK_COND_INVALID_CERT_INFO = 62,
	HTML_TEMPLATE_COMPONENT_IDENTIFIER_INVALID = -1
} HTML_TEMPLATE_COMPONENT_IDENTIFIER;

typedef struct _HTML_TEMPLATE_COMPONENT {
	HTML_TEMPLATE_COMPONENT_IDENTIFIER identifier;
	void *content;
} HTML_TEMPLATE_COMPONENT;

char *HtmlComponentEnabled;
char *HtmlComponentDisabled;

typedef struct _HTML_TEMPALTE_TABLE_INFO {
	bool inTable;
	size_t currentComponentIteration;
	size_t tableObjectIteration;
	ssize_t tableHeadOrItemIteration;
	void *tableObject;
} HTML_TEMPALTE_TABLE_INFO;

typedef struct _HTML_TEMPLATE_TABLE_STATS_GEO {
	const char *countryCode;
	uint64_t count;
} HTML_TEMPLATE_TABLE_STATS_GEO;


HTML_TEMPLATE_COMPONENT *HtmlTemplateHead;
size_t HtmlTemplateHeadSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateFoot;
size_t HtmlTemplateFootSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateHome;
size_t HtmlTemplateHomeSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateUProxies;
size_t HtmlTemplateUProxiesSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateProxies;
size_t HtmlTemplateProxiesSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateProxySources;
size_t HtmlTemplateProxySourcesSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateStats;
size_t HtmlTemplateStatsSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateCheck;
size_t HtmlTemplateCheckSize;

HTML_TEMPLATE_COMPONENT *HtmlTemplateTools;
size_t HtmlTemplateToolsSize;

void HtmlTemplateParse(FILE *hFile, HTML_TEMPLATE_COMPONENT **Template, size_t *SizeRef, config_setting_t *CfgRoot);
void HtmlTemplateLoadAll();
void HtmlTemplateBufferInsert(struct evbuffer *Buffer, HTML_TEMPLATE_COMPONENT *Components, size_t Size, INTERFACE_INFO Info, HTML_TEMPALTE_TABLE_INFO TableInfo);
void HtmlTemplateMimeTypesInit();